change yaml file

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,9 +1,52 @@
+# # name: CI
+
+# # on:
+# #   push:
+# #     branches: ["main"]
+# #   # pull_request:
+
+# # jobs:
+# #   ci:
+# #     runs-on: ubuntu-latest
+
+# #     steps:
+# #       - name: Checkout
+# #         uses: actions/checkout@v4
+
+# #       - name: Set up Python
+# #         uses: actions/setup-python@v5
+# #         with:
+# #           python-version: "3.12"
+
+# #       - name: Install dependencies
+# #         run: |
+# #           python -m pip install --upgrade pip
+# #           pip install -r requirements.txt
+          
+
+# #       - name: Build Docker images
+# #         run: |
+# #           docker compose  up --build -d
+
+# #       # - name: verify fastapi
+# #       #   run: |
+# #       #     uvicorn app.main:app --reload 
+
+
+# #       - name: check running continer
+# #         run: 
+# #           docker ps    
+
+# #       - name: check logs
+# #         if: failure()
+# #         run:
+# #           docker compose logs    
+
 # name: CI
 
 # on:
 #   push:
 #     branches: ["main"]
-#   # pull_request:
 
 # jobs:
 #   ci:
@@ -13,83 +56,117 @@
 #       - name: Checkout
 #         uses: actions/checkout@v4
 
-#       - name: Set up Python
-#         uses: actions/setup-python@v5
-#         with:
-#           python-version: "3.12"
-
-#       - name: Install dependencies
+#       - name: Build + start services (docker compose)
 #         run: |
-#           python -m pip install --upgrade pip
-#           pip install -r requirements.txt
-          
+#           docker compose up --build -d
 
-#       - name: Build Docker images
+#       - name: Show running containers
 #         run: |
-#           docker compose  up --build -d
+#           docker ps
+#           docker compose ps
 
-#       # - name: verify fastapi
-#       #   run: |
-#       #     uvicorn app.main:app --reload 
+#       - name: Run DB migrations (inside fastapi container)
+#         run: |
+#           docker compose exec -T fastapi alembic upgrade head
 
+#       - name: Verify FastAPI (/docs)
+#         run: |
+#           for i in {1..40}; do
+#             if curl -fsS http://localhost:8000/docs >/dev/null; then
+#               echo "FastAPI is up"
+#               exit 0
+#             fi
+#             echo "Waiting for FastAPI... ($i)"
+#             sleep 2
+#           done
+#           echo "FastAPI did not start in time"
+#           exit 1
 
-#       - name: check running continer
-#         run: 
-#           docker ps    
-
-#       - name: check logs
+#       - name: Logs on failure
 #         if: failure()
-#         run:
-#           docker compose logs    
+#         run: |
+#           docker ps
+#           docker compose ps
+#           docker compose logs --no-color
 
-name: CI
+#       # - name: Shutdown
+#       #   if: always()
+#       #   run: |
+#       #     docker compose down -v
+
+name: CI CD Pipeline Integration
 
 on:
   push:
-    branches: ["main"]
+    branches:
+    - main
+
 
 jobs:
-  ci:
+  test:
     runs-on: ubuntu-latest
 
+    # env:
+    #   CI: "true"
+    #   DB_USER: ${{ secrets.DB_USER }}
+    #   DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
+    #   DB_HOST: ${{ secrets.DB_HOST }}
+    #   DB_PORT: ${{ secrets.DB_PORT }}
+    #   DB_NAME: ${{ secrets.DB_NAME }}
+
     steps:
-      - name: Checkout
+      - name: Check repository
         uses: actions/checkout@v4
 
-      - name: Build + start services (docker compose)
-        run: |
-          docker compose up --build -d
+      - name: python setup
+        uses: actions/setup-python@v5
+        with:
+          python-version: "3.10"
 
-      - name: Show running containers
+      - name: Install dependencies
         run: |
-          docker ps
-          docker compose ps
+          python -m pip install --upgrade pip
+          pip install fastapi sqlalchemy psycopg2-binary python-dotenv uvicorn
 
-      - name: Run DB migrations (inside fastapi container)
+      - name: Verify FastAPI app
         run: |
-          docker compose exec -T fastapi alembic upgrade head
+          python --version
 
-      - name: Verify FastAPI (/docs)
-        run: |
-          for i in {1..40}; do
-            if curl -fsS http://localhost:8000/docs >/dev/null; then
-              echo "FastAPI is up"
-              exit 0
-            fi
-            echo "Waiting for FastAPI... ($i)"
-            sleep 2
-          done
-          echo "FastAPI did not start in time"
-          exit 1
-
-      - name: Logs on failure
-        if: failure()
-        run: |
-          docker ps
-          docker compose ps
-          docker compose logs --no-color
-
-      # - name: Shutdown
-      #   if: always()
+      # - name: Debug docker username
       #   run: |
-      #     docker compose down -v
+      #     echo "Docker user is: '${{ secrets.DOCKER_USERNAME }}'"
+
+      - name: Set up Docker
+        uses: docker/setup-buildx-action@v2
+
+      - name: Log in to Docker Hub
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
+
+      - name: Build backend image
+        run: |
+          docker build -f Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/fastapi:latest .
+
+      - name: Build database image
+        run: |
+          docker build -f Dockerfile.worker -t ${{ secrets.DOCKERHUB_USERNAME }}/radis:latest .
+
+      - name: Push Docker_backend image
+        run: |
+           docker push ${{ secrets.DOCKERHUB_USERNAME }}/fastapi:latest
+
+      - name: Push Docker_database image
+        run: |
+           docker push ${{ secrets.DOCKERHUB_USERNAME }}/radis:latest
+
+      - name: Deploy application
+        run: |
+           docker pull ${{ secrets.DOCKERHUB_USERNAME }}/fastapi:latest
+           docker pull ${{ secrets.DOCKERHUB_USERNAME }}/radis:latest
+
+
+      - name: Run docker application
+        run: |
+          docker compose up -d --build
